// The fifty trees in the guide, with the Latin name used to search Commons and
// the `search` override where a cultivar has no page of its own to lead from.
// Shared so the habit/leaf fetcher and the bark fetcher cannot drift apart.
export const SPECIES_SOURCES = [
	{ id: 'oak', latin: 'Quercus robur' },
	{ id: 'sessile-oak', latin: 'Quercus petraea' },
	{ id: 'holm-oak', latin: 'Quercus ilex' },
	{ id: 'birch', latin: 'Betula pendula' },
	{ id: 'downy-birch', latin: 'Betula pubescens' },
	{ id: 'rowan', latin: 'Sorbus aucuparia' },
	{ id: 'whitebeam', latin: 'Sorbus aria' },
	{ id: 'wild-service', latin: 'Sorbus torminalis' },
	{ id: 'beech', latin: 'Fagus sylvatica' },
	{ id: 'hornbeam', latin: 'Carpinus betulus' },
	{ id: 'ash', latin: 'Fraxinus excelsior' },
	{ id: 'holly', latin: 'Ilex aquifolium' },
	{ id: 'yew', latin: 'Taxus baccata' },
	{ id: 'pine', latin: 'Pinus sylvestris' },
	{ id: 'larch', latin: 'Larix decidua' },
	{ id: 'spruce', latin: 'Picea abies' },
	{ id: 'douglas-fir', latin: 'Pseudotsuga menziesii' },
	{ id: 'juniper', latin: 'Juniperus communis' },
	{ id: 'hawthorn', latin: 'Crataegus monogyna' },
	{ id: 'blackthorn', latin: 'Prunus spinosa' },
	{ id: 'wild-cherry', latin: 'Prunus avium' },
	{ id: 'bird-cherry', latin: 'Prunus padus' },
	{ id: 'crab-apple', latin: 'Malus sylvestris' },
	{ id: 'chestnut', latin: 'Aesculus hippocastanum' },
	{ id: 'sweet-chestnut', latin: 'Castanea sativa' },
	{ id: 'sycamore', latin: 'Acer pseudoplatanus' },
	{ id: 'norway-maple', latin: 'Acer platanoides' },
	{ id: 'field-maple', latin: 'Acer campestre' },
	{ id: 'london-plane', latin: 'Platanus x hispanica' },
	{ id: 'lime', latin: 'Tilia cordata' },
	{ id: 'elder', latin: 'Sambucus nigra' },
	{ id: 'hazel', latin: 'Corylus avellana' },
	{ id: 'alder', latin: 'Alnus glutinosa' },
	{ id: 'wych-elm', latin: 'Ulmus glabra' },
	{ id: 'goat-willow', latin: 'Salix caprea' },
	{ id: 'white-willow', latin: 'Salix alba' },
	{ id: 'aspen', latin: 'Populus tremula' },
	{ id: 'black-poplar', latin: 'Populus nigra' },
	{ id: 'walnut', latin: 'Juglans regia' },
	{ id: 'box', latin: 'Buxus sempervirens' },
	// batch G — the planted trees, taking the guide to fifty. `search` overrides
	// the Latin name where the cultivar has no page of its own to lead from.
	{ id: 'sitka-spruce', latin: 'Picea sitchensis' },
	{ id: 'common-lime', latin: 'Tilia × europaea', search: 'Tilia europaea' },
	{ id: 'crack-willow', latin: 'Salix fragilis' },
	{ id: 'leylandii', latin: 'Cupressus × leylandii', search: 'Cupressocyparis leylandii' },
	{ id: 'monkey-puzzle', latin: 'Araucaria araucana' },
	{ id: 'giant-redwood', latin: 'Sequoiadendron giganteum' },
	{ id: 'cedar-of-lebanon', latin: 'Cedrus libani' },
	{ id: 'weeping-willow', latin: 'Salix babylonica', search: 'Salix sepulcralis' },
	{ id: 'lombardy-poplar', latin: 'Populus nigra', search: 'Populus nigra Italica' },
	{ id: 'ornamental-cherry', latin: 'Prunus serrulata', search: 'Prunus Kanzan' }
];
